{% set name = "FormEncode" %}
{% set version = "2.0.0" %}
{% set hash_value = "f2eb92297417eb64e4aa8e368783a5ac1311e385d4f3ff3a181090608ea83711" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash_value }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - python >=3.6
    - six

test:
  imports:
    - formencode

about:
  home: http://formencode.org
  license: MIT
  license_file: LICENSE.txt
  summary: 'HTML form validation, generation, and conversion package'
  dev_url: https://github.com/formencode/formencode

extra:
  recipe-maintainers:
   - windelbouwmanbosch
   - windelbouwman
   - synapticarbors
